config/routes.rb
Rails.application.routes.draw do
  resources :news do
  	resources :news_comments, path: 'comments'
  end

	root 'news#index'
end

app/models/news.rb
class News < ApplicationRecord
	#belongs_to :author, foreign_key: "user_id", class_name: "User"
  has_many :comments, class_name: "NewsComment", dependent: :destroy

	# Validates
  # validates :author, presence: true
  validates :headline, presence: true
  validates_length_of :headline, :maximum => 200
  #validates :subhead, presence: true
  validates_length_of :subhead, :maximum => 200
  validates :copy, presence: true

  # Shorts
  def short_headline(len = 200)
  	self.headline.truncate(len)
  end
  def short_copy(len = 500)
  	self.copy.truncate(len)
  end

  def as_json(*args)
    super.tap { |hash|
      hash["title"] = hash.delete "headline"
      hash["subtitle"] = hash.delete "subhead"
      hash["body"] = hash.delete "copy"
      hash["body"] = hash.delete "short_copy" if hash["short_copy"]
    }
  end
  
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  def index
    @news = News.all.select(:id, :headline, :subhead, :copy, :created_at).order('created_at DESC')
    render json: @news.as_json(except: [:copy], methods: [:short_copy]), status: :ok
  end

  # GET /news/:id
  def show
    render json: @news.as_json(except: [:updated_at]), status: :ok
  end

  # POST /news
  def create
    @news = News.new(news_params)

    if @news.save
      render json: @news.as_json(except: [:updated_at]), status: :created
    else
      render json: @news.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /news/:id
  def update
    if @news.update(news_params)
      render json: @news.as_json(except: [:updated_at]), status: :ok
    else
      render json: @news.errors, status: :unprocessable_entity
    end
  end

  # DELETE /news/:id
  def destroy
    success = @news.as_json(except: [:updated_at])
    if @news.destroy
      render json: success, status: :ok
    else
      render json: {"error": "news already deleted"}, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params["news"]["headline"] = params["title"] if params["title"]
      params["news"]["subhead"] = params["subtitle"] if params["subtitle"]
      params["news"]["copy"] = params["body"] if params["body"]
      params.require(:news).permit(:headline, :subhead, :copy)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= bootstrap_form_for(news) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.text_field :headline, autofocus: true, autocomplete: "off" %>
  <%= f.text_area :subhead, autocomplete: "off", rows: "3" %>
  <%= f.text_area :copy, autocomplete: "off", rows: "8" %>

  <%= f.submit class: "btn btn-success center-block" %>
<% end %>

app/views/news/_new_comment.html.erb
<div class="row">
  <div class="col-md-8">
		<%= bootstrap_form_for([@news, @news.comments.build], remote: true) do |f| %>
		  <%= render 'shared/error_messages', object: f.object %>
		  <%= f.text_field :author, autocomplete: "name", label: "Full Name", required: true, value: user_signed_in? &&current_user.name + " " + current_user.last_name || "" %>
		  <%= f.text_area :comment, rows: "4", required: true %>

		  <%= f.submit "Publish comment", class: "btn btn-success" %>
		<% end %>
  </div>
</div>

app/views/news/_show_comments.html.erb
<font size="5">
	<%= pluralize(@comments.count, "comment") %>
</font>

<div class="row">
	<ul id="comments" class="comments">
	  <% if @comments.empty? %>
	    <li>
	      <h2>There are no comments for this new.</h2>
	    </li>
	  <% end %>

	  <% @comments.each do |comment| %>
	    <li>
	      <div class="col-xs-2">
	        <%= comment.author %>
	        <br>
	        <small><i><%= time_ago_in_words(comment.created_at) %> ago</i></small>
	      </div>
	      <div class="col-xs-10">
	        <%= simple_format(raw comment.comment) %>
	      </div>
	    </li>
	  <% end %>
	</ul>
</div>

<hr>

<h3>New Comment</h3>
<%= render "new_comment" %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>

<br>
<%= link_to 'Back', @news, class: "btn btn-primary col-xs-3" %>
<%= link_to 'Delete', @news, data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger col-xs-3 col-xs-offset-6" %>

app/views/news/index.html.erb
<% provide(:title, 'News') %>

<%= link_to 'New News', new_news_path, class: "btn btn-success", style: "float: right" if user_signed_in? %>

<h1>News</h1>

<div class="text-right">
  <%= will_paginate @news, renderer: BootstrapPagination::Rails %>
</div>
<div class="row">
  <% @news.each do |news| %>
    <%= link_to(news, class: "news-link") do %>
      <div class="col-xs-12">
        <div class="panel panel-info">
          <div class="panel-heading">
            <% if user_signed_in? %>
              <div class="row">
                <div class="col-xs-12">
                  <object><%= link_to "Edit", edit_news_path(news), class: "btn btn-primary col-xs-3" %></object>
                  <object><%= link_to "Delete", news, data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger col-xs-3 col-xs-offset-6" %></object>
                </div>
              </div>
            <% end %>
            <h4><%= news.headline %></h4>
          </div>
          <div class="panel-body">
            <%= simple_format(news.subhead) %>
            <hr>
            <small><%= simple_format(news.short_copy) %></small>
          </div>
          <div class="panel-footer container-fluid">
            <div class="text-left" style="display: inline-block;">
              <%= news.created_at.strftime("%d-%m-%y %H:%M") %>
            </div>
            <div class="text-right" style="display: inline-block; float: right;">
              <span class="badge"><%= pluralize(news.comments.count, "comment")%></span>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<div class="text-right">
  <%= will_paginate @news, renderer: BootstrapPagination::Rails %>
</div>

app/views/news/list.html.erb
<% provide(:title, "News") %>

<%= link_to 'New News', new_news_path, class: "btn btn-success", style: "float: right" %>

<h1>News</h1>

<div class="text-right">
  <%= will_paginate @news, renderer: BootstrapPagination::Rails %>
</div>

<ul class="news">
  <li class="h-title text-center" style="font-weight:bold">
    <div style="width: 35%;">
      Titulo
    </div>
    <div style="width: 20%;">
      Autor
    </div>
    <div style="width: 20%;">
      Fecha
    </div>
    <div style="width: 25%;">
      Acciones
    </div>
  </li>
  
  <% @news.each do |news| %>
    <%= link_to news do %>
      <li class="h-title text-center">
        <div style="width: 35%; margin-left: 10px;" class="text-left">
          <%= news.short_headline 30 %>
        </div>
        <div style="width: 20%;">
          <%= news.author.name + " " + news.author.last_name %>
        </div>
        <div style="width: 20%;">
          <%= news.created_at.strftime("%d-%m-%y %H:%M") %>
        </div>
        <div style="width: 25%;">
          <object><%= link_to "Edit", edit_news_path(news), class: "btn btn-primary" %></object>
          <object><%= link_to "Delete", news, data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger" %></object>
        </div>
      </li>
    <% end %>
  <% end %>
</ul>

<div class="text-right">
  <%= will_paginate @news, renderer: BootstrapPagination::Rails %>
</div>

app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<% provide(:title, @news.short_headline(30)) %>

<div class="row">
	<% if user_signed_in? %>
		<%= link_to "Edit", edit_news_path(@news), class: "btn btn-primary col-xs-3" %></object>
  	<%= link_to "Delete", @news, data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger col-xs-3 col-xs-offset-6" %>
  	<br>
		<br>
  <% end %>

	<br>
	<div class="col-xs-12">
			<font size="5">
				<%= @news.headline %>
			</font>
			<br>
			<br>
			<font size="3">
				<%= simple_format(@news.subhead) %>
			</font>
			<hr>
			<font size="2">
				<%= simple_format(@news.copy) %>
			</font>
			<br>
			<br>
			<font size="1" style="float: right;">
				<%= @news.created_at.strftime("%d-%m-%y %H:%M") %> - <i><%= @news.author.name + " " + @news.author.last_name %></i>
			</font>
			<hr style="height:2px;border:none;color:#333;background-color:#333;">

		  <%= render "show_comments" %>
			<br>
	</div>
</div>

<%= link_to 'Back', news_index_path, class: "btn btn-primary col-xs-3" %>